language: python
python:
  - "3.6"

#Command to install dependencies
env:
  global:
    - CODECOV_TOKEN="8f3efc4a-4ba3-4f02-b1d6-e1a77c66ab48"
install:
  - pip install -r requirements.txt
  - pip install coveralls

#Command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - python3 -pytest -v --cov app --cov-report
  - coverage report

after_success:
  - coveralls
  - codecov



  